### ISSUE TITLE
报错信息如下，请指教。

### ISSUE THREAD

**Issue by kongfanyu** [AI4Finance-Foundation/FinGPT#71]
Mac系统，CPU  i7  内存16G， 下载了001-007的文件；运行报错：
/Users/kongfanyu/Downloads/MyFinGPT/venv/bin/python /Users/kongfanyu/Downloads/MyFinGPT/fingpt/FinGPT-v3/test.py 
Traceback (most recent call last):
  File "/Users/kongfanyu/Downloads/MyFinGPT/fingpt/FinGPT-v3/test.py", line 13, in <module>
    model = AutoModel.from_pretrained(base_model, trust_remote_code=True, device_map="auto")
  File "/Users/kongfanyu/Downloads/MyFinGPT/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/kongfanyu/Downloads/MyFinGPT/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/Users/kongfanyu/Downloads/MyFinGPT/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3296, in _load_pretrained_model
    raise ValueError(
**ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.**

进程已结束,退出代码1

**Comment by oliverwang15** [comment]
这个应该是GPU显存不足所以转用内存进行推理，解决方案可以参考[这里](https://zhuanlan.zhihu.com/p/647755430)和[这里](https://zhuanlan.zhihu.com/p/649272911?utm_id=0)。不过用内存+CPU推理的话速度可能会比较慢。
